googlefonts/noto-source

- build.sh
The most important thing here I think is that we're installing dependencies locally.
> Build fixes

- build.sh
Depends on https://github.com/googlei18n/fontmake/pull/156
> Interpolate master binaries for plist source

- .travis.yml
- build.sh
- build_travis.sh
Very much a work in progress, but this should work as a proof-of-concept. Can test with some contrived source change after it's merged.
> Staging scheme for continuous integration

- .travis.yml
- build_travis.sh
Fixes a couple of things to allow using notodiff, and also generates some simple HTML to summarize changes (can be found in gh-pages branch).
> CI adjustments

- src/NotoSansChakma/NotoSansChakma-MM.glyphs
(overlooked this in previous update)
> Update version of NotoSansChakma to 2.000.

- src/NotoSerifMyanmar/NotoSerifMyanmar-MM.glyphs
> Fix myanmar names

- util.sh
> Add Malayalam UI to list of sources that build UI from a separate plist

- util.sh
To prepare for upcoming Kannada Sans delivery
> Add Kannada Sans UI to list of sources that build UI from separate plist

- src/NotoSansKayahLi.glyphs
Updates NotoSansKayahLi.glyphs with Bold master and Medium, SemiBold and Bold instances.
> Updates NotoSansKayahLi.glyphs

- build
- util.sh
updated build and util.sh to handle designspace.
I'm not sure how it fits the overall design so comments will be very welcome
Also I realized that the fontmake command was creating only the master_*tf files, so I'm copying these to instance_*tf directories; maybe there's a better way to do it
> updated build and util.sh to handle designspace

- src/NotoSansArabic-MM.glyphs
Fixed issues reported in https://github.com/googlefonts/noto-fonts/issues/1854
> Fixed minor issues in Noto Sans Arabic

- src/NotoSansLao-MM.glyphs
Outline glitch in NotoSansLao fix ExtraCondensedBlack NotoSansLaoUI looks good https://github.com/googlefonts/noto-fonts/issues/1904
https://github.com/googlefonts/noto-source/issues/245
> Outline glitch in NotoSansLao fix

- src/NotoKufiArabic.glyphs
Diacritics overlap in U+0646 final form fixed https://github.com/googlefonts/noto-fonts/issues/1888
> Diacritics overlap in U+0646 final form fix

- src/NotoKufiArabic.glyphs
Above diacritics overlap the dots above issue fixed for all weights and forms U+076B, U+0763, U+075C, U+075D, U+076D. https://github.com/googlefonts/noto-fonts/issues/1589
> Above diacritics overlap the dots fixed

- src/NotoSansOlChiki.glyphs
Added Unicode Character 'INDIAN RUPEE SIGN' (U+20B9) to NotoSansOlChiki.glyphs
https://github.com/googlefonts/noto-fonts/issues/1769
> Added Unicode Character U+20B9

- src/NotoSerifGujarati-MM.glyphs
'GUJARATI DIGIT SIX' (U+0AEC) NotoSerifGujarati shape change proposal (full hook)
https://github.com/googlefonts/noto-fonts/issues/1768
> U+0AEC NotoSerifGujarati shape change proposal (full hook)

- src/NotoKufiArabic.glyphs
Changed U+06E0 to look like oval shaped zero
https://github.com/googlefonts/noto-fonts/issues/1903
> Changed U+06E0 to look like oval shaped zero

- src/NotoSansGunjalaGondi.glyphs
Added 00A0 to NotoSansGunjalaGondi
https://github.com/googlefonts/noto-fonts/issues/1909
> Added 00A0 to NotoSansGunjalaGondi

- src/NotoSerifDogra.glyphs
Added 00A0 to NotoSerifDogra
https://github.com/googlefonts/noto-fonts/issues/1909
> Added 00A0 to NotoSerifDogra

- src/NotoSansMasaramGondi.glyphs
Added 00A0 to NotoSansMasaramGondi
https://github.com/googlefonts/noto-fonts/issues/1909
> Added 00A0 to NotoSansMasaramGondi

- src/NotoTraditionalNushu.glyphs
Added 00A0 to NotoTraditionalNushu
https://github.com/googlefonts/noto-fonts/issues/1909
> Added 00A0 to NotoTraditionalNushu

- src/NotoKufiArabic.glyphs
Wrong anchors U+065E fix
https://github.com/googlefonts/noto-fonts/issues/1893
> Wrong anchors U+065E NotoKufiArabic

- src/NotoKufiArabic.glyphs
- src/NotoSansGunjalaGondi.glyphs
- src/NotoSansLao-MM.glyphs
- src/NotoSansMasaramGondi.glyphs
- src/NotoSansOlChiki.glyphs
- src/NotoSerifDogra.glyphs
- src/NotoSerifGujarati-MM.glyphs
- src/NotoTraditionalNushu.glyphs
Updated version numbers to account for the recent changes
> Updated version numbers to account for the recent changes

- src/NotoKufiArabic.glyphs
ASCII numerals added to NotoKufiArabic
https://github.com/googlefonts/noto-fonts/issues/1884
U+06D1 initial and medial glyph added to NotoKufiArabic
https://github.com/googlefonts/noto-fonts/issues/1040
> Ascii numerals added some other fixes

- src/NotoSansSymbols2/NotoSansSymbols2-Regular.ufo/glyphs/enclosingkeycapcomb.glif
- src/NotoSansSymbols2/NotoSansSymbols2-Regular.ufo/glyphs/enclosingscreencomb.glif
- src/NotoSansSymbols2/NotoSansSymbols2-Regular.ufo/glyphs/u102E_0.glif
- src/NotoSansSymbols2/NotoSansSymbols2-Regular.ufo/lib.plist
> updated NotoSansSymbols2

- src/NotoNaskhArabic.glyphs
- src/NotoNaskhArabicUI.glyphs
updating NotoNaskhArabicUI and NotoNaskhArabic
> updating NotoNaskhArabicUI and NotoNaskhArabic

- src/NotoNaskhArabic/NotoNaskhArabic-for-edit.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI-for-edit.glyphs
Minor edit to form the ligature U+FDF2 when form of heh U+06C1 Arabic Letter Heh Goal exist.
> NotoNaskhArabic and NotoNaskhArabicUI FDF2 forming

- src/NotoSansSignWriting/Noto Sans SignWriting GDEF.txt
- src/NotoSansSignWriting/Noto Sans SignWriting GPOS.txt
renamed nbspace to uni00A0 in NotoSansSignWriting
> renamed nbspace to uni00A0 in NotoSansSignWriting

- src/NotoRashiHebrew.glyphs
fixed https://github.com/googlefonts/noto-fonts/issues/1942
fixed https://github.com/googlefonts/noto-fonts/issues/1639
fixed https://github.com/googlefonts/noto-fonts/issues/1638
fixed https://github.com/googlefonts/noto-fonts/issues/1636
> NotoRashiHebrew fixes

- src/NotoKufiArabic.glyphs
Applying http://www.unicode.org/versions/Unicode13.0.0/ch09.pdf to FDF2 to make Kufi font consistent with other fonts Fixed https://github.com/googlefonts/noto-fonts/issues/1879 
U+06BD initial and medial fixed diacritics positioning issue
Fixed https://github.com/googlefonts/noto-fonts/issues/1188
Fixing high priority  “ لا لا لأ لآ لإ لٱ”  https://github.com/googlefonts/noto-fonts/issues/1098
> NotoKufiArabic fixes

- src/NotoNaskhArabic/NotoNaskhArabic-for-edit.glyphs
- src/NotoNaskhArabic/NotoNaskhArabic.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI-for-edit.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI.glyphs
Fixed https://github.com/googlefonts/noto-fonts/issues/1182
Fixed https://github.com/googlefonts/noto-fonts/issues/1187
Other minor bugs fixed
> Noto sans arabic fonts

- src/NotoNaskhArabic/NotoNaskhArabic-for-edit.glyphs
- src/NotoNaskhArabic/NotoNaskhArabic.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI-for-edit.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI.glyphs
Fix https://github.com/googlefonts/noto-fonts/issues/1941
Fix https://github.com/googlefonts/noto-fonts/issues/1987
> NotoNaskhArabic fonts fixes

- test/LGC/fontdiff-gr-20210324.html
updated NotoSans designer, version fields
> updated NotoSans designer, version fields

- src/NotoNaskhArabic/NotoNaskhArabic.glyphs
Fixes googlefonts/noto-fonts#2085.
> NotoNaskhArabic: locl_arabURD_arabKSH_1 for URD and KSH only

- src/NotoSerifGrantha/Noto Serif Grantha GPOS.txt
- src/NotoSerifGrantha/NotoSerifGrantha.glyphs
Fix for https://github.com/googlefonts/noto-fonts/issues/2089
> Fix Grantha Serif tri glyph

- src/NotoSansOldHungarianUI/NotoSansOldHungarianUI-Regular.glyphs
On branch oldhungui
Changes to be committed:
new file:   src/NotoSansOldHungarianUI/NotoSansOldHungarianUI-Regular.glyphs
> Resolved all rendering problem of NotoSansOldHungarianUI

- src/NotoSansBrahmi.glyphs
The Monotype source crept back into the repository instead of the re-engineered one. This is the new version!
> Fix Brahmi font source

- src/NotoSansSharada.glyphs
This fixes the kerning problem (see test d2fa00e in #433)
> Fix languagesystem

- src/NotoSansLimbu.glyphs
> Make Limbu marks spacing

- src/NotoSansHanunoo.glyphs
This makes sure that Hanunoo goes through the USE and gets syllable formation. See test 84e5a12 in #433.
> Add languagesystem to Hanunoo

- test/fontbakery/bengali.json
This is the first multiple-master conversion I've done; please test more carefully... :-)
- Existing and autogenerated tests for Bengali
- Convert Bengali to pure-Glyphs source
- Change version and copyright date
> Convert Bengali to pure-Glyphs source

- src/NotoSerifMakasar-Regular.ufo/glyphs/contents.plist
- src/NotoSerifMakasar-Regular.ufo/glyphs/uni11E_E_5.glif
- src/NotoSerifMakasar-Regular.ufo/glyphs/uni25C_C_.glif
- src/NotoSerifMakasar-Regular.ufo/lib.plist
Regarding #googlefonts/noto-fonts#2222 and #googlefonts/noto-fonts#2221.
> Fix Makasar open corners and missing glyph

- src/NotoSerifToto-MM.glyphs
Fixes googlefonts/noto-fonts#2193
> Reorder mkmk lookups in Toto

- src/NotoNastaliqUrdu.glyphs
- test/fontbakery/nastaliq.json
- Tests for googlefonts/noto-fonts#2234 and googlefonts/noto-fonts#1588
- Fix googlefonts/noto-fonts#2234
> Fix Nastaliq theograph formation

- src/NotoSerifDivesAkuru.glyphs
Should solve #googlefonts/noto-fonts/issues/2224 and #googlefonts/noto-fonts/issues/2227.
> Improves mark positioning and adds missing touching conjunct

- src/NotoSerifGrantha.glyphs
- test/fontbakery/grantha.json
- Add fontdiffenator tests to fontbakery
- Fix mark-to-mark positioning
> Fix Grantha Serif mark-to-mark positioning

- src/NotoSerifBalinese.glyphs
- test/fontbakery/balinese.json
- Convert fontdiff tests to fontbakery
- Fix category of spacing marks
> Fix category of Balinese spacing marks

- test/fontbakery/kannada.json
- Convert some fontdiff tests to fontbakery
- Fix category of evowelsignknda
> Fix category of Kannada e vowel sign

- src/NotoSansKharoshthi.glyphs
- test/fontbakery/kharoshthi.json
- Convert fontdiff tests to fontbakery
- Just rename the anchor, that'll fix it. ¯\_(ツ)_/¯
> Fix Kharoshthi subjoined ya anchor attachment
