googlefonts/noto-source

- build.sh
- src/NotoSansDevanagari/NotoSansDevanagari.plist
- src/NotoSansMyanmar/NotoSansMyanmar-MM.plist
- src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.plist
One thing to note is that there is no DevanagariUI master output, so now many of the feature files are unused. But it seems we may want a different way to apply MTI features later anyways (since we need to interpolate them after compilation) so I didn't worry about that too much for now.
> Apply MTI to masters

- src/NotoSansArmenian-MM.glyphs
- src/NotoSansEthiopic-MM.glyphs
- src/NotoSansGeorgian-MM.glyphs
- src/NotoSansHebrew-MM.glyphs
- src/NotoSansThai-MM.glyphs
- src/NotoSerifArmenian-MM.glyphs
- src/NotoSerifGeorgian-MM.glyphs
- src/NotoSerifHebrew-MM.glyphs
- src/NotoSerifThai-MM.glyphs
- Updates version numbers to 1.9XX for prerelease fonts in anticipation of
'version 2.000' for the release version.
- For phase 3 we will no longer use a 'uh' suffix in the version string to
indicate unhinted outlines, nor indicate hinted/unhinted in the description
text.  Now there is no tag, if we generate explicitly hinted fonts we can
tag those. As the existing fonts did not do this anyway, no changes to the
source were necessary.
- Changes naming to use 'Condensed', 'SemiCondensed', 'ExtraBold' instead
of 'Cond' (and other variants), 'Narrow', 'Extra Bold', etc.
- Tweaks to manufacturerURL, designer fields to match lint.
- Renames fonts generated by NotoSansUIMono-MM.glyphs to omit 'UI' from
name.
> Swat versions, names, name table data.

- .gitignore
- build
I don't want that my global python configuration is modified when I build Noto fonts.
It's better to avoid doing any `sudo` and even `pip install --user`, and let the user decide what to do.
If pip is missing, we just fail, suggest a course of action and direct the user to the pip documentation.
If pip is installed but virtualenv is not, we can install virtualenv in our working directory with --target option, and use it to bootstrap our virtual environment.
Also, before installing fontmake, it's a good idea to make sure the submodule is up-to-date.
> don't install anything globally, bootstrap virtualenv into working dir

- build
The default pip upgrade strategy is "eager", which means dependencies
are upgraded regardless of whether the currently installed version
satisfies the requirements of the upgraded package(s).
This make the setup undeterministic (as it dependes on what is currently
latest available versions on PyPI), and risks failing when newer
versions of the dependencies break the API.
We use requirements.txt to pin down fontmake's dependencies to specific
versions, and use git submodule to pin down fontmake's version itself.
Fixes https://github.com/googlei18n/noto-source/issues/72
> [setup] don't pip install --upgrade fontmake; just pip install

- src/NotoSansAdlamUnjoined/NotoSansAdlamUnjoined-MM.glyphs
- src/NotoSansArmenian-MM.glyphs
- src/NotoSerifArmenian-MM.glyphs
Previously these were 2.900+, because the phase 2 versions had major
versions of 2.
This seems like a good time to unify the major version numbering to be
consistent across the noto phase, so we will keep the major version at
2 but bump the minor.  The minor of 040 was chosen so there's a bump
in the second digit, since we're also converting to a three-digit minor
with this phase of Noto.
> Update Armenian version numbers for release.

- build_merged_noto.py
This is still work in progress:
* the blacklist of currently unmergeable shards is incomplete;
* we need to find a solution for the shards whose sources do not have
the same design masters as the Latin/Greek/Cyrillic base font.
Missing Semibold masters can probably be automatically interpolated,
but this script does not do this yet.
> Clean up the script for building merged Noto fonts

- src/NotoNastaliqUrdu/NotoNastaliqUrdu-MM.glyphs
- util.sh
Fixes a compilation issue reported at https://github.com/googlei18n/fontmake/issues/352
NotoNastaliqUrdu-MM.glyphs does not have interpolatable outlines or GPOS, so it doesn't make sense to call fontmake with -i or --interpolate-binary-layout options in that case.
We can build static OTFs and TTFs straight from the master UFOs.
The only thing that distinguishes the instances in NotoNastaliqUrdu-MM.glyphs from the respective masters is that in Glyphs.app only the instances have OS/2 Weight and Width clearly defined, whereas masters do not.
We work around this by setting `openTypeOS2WeightClass` and `openTypeOS2WidthClass` custom parameters ourselves directly on the _masters_. Even though in Glyphs.app these will appear greyed out (as they are not normally assigned to masters but to …
> do not attempt to interpolate Nastaliq Urdu

- src/NotoSansOldNorthArabian-MM.glyphs
- src/NotoSansSoraSompeng-MM.glyphs
These source files are the only two for which the `familyName` attribute uses a shortened form that doesn't match the respective file name.
This patch sets the `familyName` to the long (preferred) name, and sets the `styleMapFamilyName` to the short name.
It also removes the `preferredFamilyName`, `fileName` and `postscriptFontName` custom parameters since they are now redundant, as they are the same as the default values.
Fixes #107
> fix familyName of NotoSans Old North Arabian and Sora Sompeng

- src/NotoSansSyriac-MM.glyphs
This file contains all of Estrangela, Eastern and Western Syriac in a
single font. Applications can choose the preferred style by requesting
the corresponding OpenType language system. We’ll need this for
re-packaging Noto Sans into a single pan-Unicode font file.
The OpenType language system tags for Syriac have been registered with
Microsoft and became part of the OpenType 1.8 specification; HarfBuzz
recognizes the BCP47 script codes for Syriac and converts them to the
correct OpenType language system codes.
The font design is probably not the final version, but I’d like to
add the current version to the source repository so that
applications and operating systems can be tested early.
> Add Noto Sans Syriac

- src/NotoSansCanadianAboriginal/NotoSansCanadianAboriginal-MM.glyphs
... for the short "Noto Sans CanAborig".
Same as https://github.com/googlei18n/noto-source/commit/bc5f10d976e71c8d5eb0b48ec9a14bc1b31fa626
Fixes #107
> NotoSansCanadianAboriginal: use long familyName, add styleMapFamilyName

- README.md
- build
the fontmake version currently used in noto-source repo is quite old (v1.8.0) and needs updating.
The current fontmake requires python3.6 or greater, so I have updated the `build setup` to look for `python3` (or `python3.6` or `python3.7`) executable when creating the build environment.
> Update to latest fontmake v2, requires Python >= 3.6 

- util.sh
Add Telugu Sans UI to list of sources that build UI from separate plist
Add Javanese to skip interpolation since it currently can't be interpolated
@marekjez86 Telugu Sans UI needs to be rebuilt. The current TTFs in noto-fonts were built without the correct source files.
> Updates to build options

- src/NotoSansTifinagh/Noto Sans Tifinagh GSUB.txt
see https://github.com/googlefonts/noto-fonts/issues/1571
note: I just commented out the entire lookup table for the slant-shaping and left the shaped glyphs in the font, as this appears to be what was done to remove the shaping for U+2D4D TIFINAGH LETTER YAL.
> remove shaping behavior of U+2D4F TIFINAGH LETTER YAN

- src/NotoSansNushu/NotoSansNushu.glyphs
This adds the GlyphsApp source for https://github.com/LisaHuang2017/noto-sans-nushu by @LisaHuang2017.
Question:
- I see that quite a few of the Noto fonts with Glyphs sources are accompanied by separate files for `GDEF, GPOS, GSUB` features. Is there a typical procedure followed to produce these?
> Add source for Noto Sans Nushü

- src/NotoNaskhArabic.glyphs
- src/NotoNaskhArabicUI.glyphs
- test/Arabic/fontdiff-1885-Arabic.html
We have fixed [#1885](https://github.com/googlefonts/noto-fonts/issues/1885) regarding the issues in browsers such as Chrome 85.
It was not possible to place correctly vowel symbols in the final form of Lam+alif+hamza in NotoNaskhArabic and UI.
Therefore anchors have been added in _1029 and _1031.
Test/Arabic was used in fontdiff to confirm that this did not affect any other combinations.
The anchors were placed by referring to when vowel symbols are placed on the isolated form of Lam+alif+hamza.
This combination is used in words such as “سيملأُ ”, so we feel it is best to handle this as priority.
The tests have been added.
We will appreciate if this can be handled.
> Noto naskh arabic fix #1885

- src/NotoSansGrantha/NotoSansGrantha.glyphs
- src/NotoSerifGrantha/NotoSerifGrantha.glyphs
For some reason we originally went with the order ya-phala followed by repha, but we really should have done it the other way to visually show repha before ya-phala. This is the more accepted way. The main Unicode proposal https://unicode.org/L2/L2009/09372-grantha.pdf defines the current order (ya-phala repha) as a known aberration.
> Swap default repha-yaphala order

- src/NotoKufiArabic.glyphs
Lowered U+06E5 little more googlefonts/noto-fonts#1901
Adjusting the ring position googlefonts/noto-fonts#1897
Adding missing glyphs U+06A8 fixed googlefonts/noto-fonts#1775
Wrong glyphs for Sindhi particles Fixed googlefonts/noto-fonts#1624
Repositioned fathatan in shadda_fathatan-ar mark, fathatan was off to the right
Fixed the stroke in U+075B, in Black weight it is too close to the base, this will improve readability
> NotoKufiArabic Fixes

- src/NotoNaskhArabic/NotoNaskhArabic-for-edit.glyphs
- src/NotoNaskhArabic/NotoNaskhArabic.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI-for-edit.glyphs
- src/NotoNaskhArabicUI/NotoNaskhArabicUI.glyphs
NotoNaskhArabic 2.009 changes:
1- U+0670 aligned high cause overlap with other diacritics 
Fix https://github.com/googlefonts/noto-fonts/issues/2032 
2- U+06E5 too thin in regular and bold
Fix https://github.com/googlefonts/noto-fonts/issues/2016 
3- U+0625 Below diacritics overlap with the Hamza (Bold weight) 
Fix https://github.com/googlefonts/noto-fonts/issues/2033 
4- U+0696 wrong dot placement
Fix https://github.com/googlefonts/noto-fonts/issues/2022 
5- U+06DC missing the top anchor, above diacritics not aligning correctly (overlap)
Fix https://github.com/googlefonts/noto-fonts/issues/2034
> NotoNaskhArabic 2.009

- src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_89.glif
- src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8A_.glif
- src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8B_.glif
- src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8C_.glif
- src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_97.glif
On branch ohuUIrendering1
Changes to be committed:
modified:   src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_89.glif
modified:   src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8A_.glif
modified:   src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8B_.glif
modified:   src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_8C_.glif
modified:   src/NotoSansOldHungUI/NotoSansOldHungUI-Regular.ufo/glyphs/u10C_97.glif
> Resolve several rendering problems in source of NotoSansOldHungUI

- test/fontbakery/sinhala.json
Somehow a rogue lookupflag found its way into the ra+vowel fix lookup, preventing short ae vowels after ra.
> Fix Sinhala Ra regression

- src/NotoNastaliqUrdu.glyphs
This changes the order of lookups so that localisations occur *after* decomposition. This will allow decomposed hamza glyphs to be localised to Arabic forms.
Also, the two-dots-above glyph got moved up somehow; moving it back down again.
> Nastaliq: Localisation fixes

- test/fontbakery/telugu-serif.json
There are some small kerning changes but I think these are actually an improvement; the Monotype sources were applying kerning to two bases with a spacing mark in the middle.
> Convert Serif Telugu to pure-Glyphs source

- test/fontbakery/devanagari.json
- test/fontbakery/signwriting.json
- Apply Devanagari test only to Devanagari
- Add test for googlefonts/noto-fonts#2263
- Change order of application; fixes googlefonts/noto-fonts#2263
- Actually that deserves a new version
> Noto Sans SignWriting 2.003

- src/NotoSansGeorgian/NotoSansGeorgian-Bold.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-Condensed.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-CondensedBold.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-CondensedLight.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-CondensedSemiBold.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-Light.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-Regular.ufo/glyphs/A_n-georgian.glif
- src/NotoSansGeorgian/NotoSansGeorgian-SemiBold.ufo/glyphs/A_n-georgian.glif
I fixed the problem with [#2046](https://github.com/googlefonts/noto-fonts/issues/2046) about two little triangles at one end of the stroke.
The outline of uni1C90 was modified. The range of influence is the 4 glyphs used as components.
uni1C900301, uni1C900308, uni1C900304, uni1C9003040308
A total of 5 glyphs have been adjusted.
I ran `./build src/NotoSansGeorgian/NotoSansGeorgian.designspace` and verified that 36 ttf files were generated correctly.
I used fontdiff to run the tests in test/Georgian. We have confirmed that there are no unintended adjustments.
> Fixed issue reported in googlefonts/noto-fonts#2046

- src/NotoSansManichaean.glyphs
- Move ligatures to rclt feature. Fixes googlefonts/noto-fonts#2281
- Version/copyright bump
> Noto Sans Manichaean 2.003

- src/NotoSansElbasan.glyphs
- Add Greek Sampi. Fixes googlefonts/noto-fonts#1363
- Bump version/copyright
- Pass notofonts fontbakery profile
> Noto Sans Elbasan 2.003

- test/fontbakery/lepcha.json
- test/fontbakery/myanmar.json
Fixes some bugs introduced by 2.104:
- Fixes googlefonts/noto-fonts#2357
- Bump version (both places this time)
- Add Myanmar test suite
- Fix tests
- Fix tests
- More tests (which fail)
- Fix aa swap issue
> Noto Sans Myanmar 2.105
